//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanus.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalTranslation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalTranslation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartGarden.Localization.Resources.LocalTranslation", typeof(LocalTranslation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string ActiveMode_Title {
            get {
                return ResourceManager.GetString("ActiveMode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device name.
        /// </summary>
        public static string AddDevice_DeviceName {
            get {
                return ResourceManager.GetString("AddDevice_DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device first.
        /// </summary>
        public static string AddDevice_DeviceNamePlaceholder {
            get {
                return ResourceManager.GetString("AddDevice_DeviceNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modes.
        /// </summary>
        public static string AddDevice_ListMode {
            get {
                return ResourceManager.GetString("AddDevice_ListMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add device.
        /// </summary>
        public static string AddDevice_Title {
            get {
                return ResourceManager.GetString("AddDevice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string AddGarden_AddDevice {
            get {
                return ResourceManager.GetString("AddGarden_AddDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add garden.
        /// </summary>
        public static string AddGarden_Button {
            get {
                return ResourceManager.GetString("AddGarden_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garden created successfully.
        /// </summary>
        public static string AddGarden_GardenCreate {
            get {
                return ResourceManager.GetString("AddGarden_GardenCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garden location.
        /// </summary>
        public static string AddGarden_GardenLocal {
            get {
                return ResourceManager.GetString("AddGarden_GardenLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behind the house.
        /// </summary>
        public static string AddGarden_GardenLocalPlaceholder {
            get {
                return ResourceManager.GetString("AddGarden_GardenLocalPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garden name.
        /// </summary>
        public static string AddGarden_GardenName {
            get {
                return ResourceManager.GetString("AddGarden_GardenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garden.
        /// </summary>
        public static string AddGarden_GardenNamePlaceholder {
            get {
                return ResourceManager.GetString("AddGarden_GardenNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garden isn&apos;t created.
        /// </summary>
        public static string AddGarden_GardennotCreate {
            get {
                return ResourceManager.GetString("AddGarden_GardennotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new garden.
        /// </summary>
        public static string AddGarden_Title {
            get {
                return ResourceManager.GetString("AddGarden_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string AddModeDevice_Devices {
            get {
                return ResourceManager.GetString("AddModeDevice_Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode name.
        /// </summary>
        public static string AddModeGarden_Name {
            get {
                return ResourceManager.GetString("AddModeGarden_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AddModeGarden_NamePlaceholder {
            get {
                return ResourceManager.GetString("AddModeGarden_NamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add mode garden.
        /// </summary>
        public static string AddModeGarden_Title {
            get {
                return ResourceManager.GetString("AddModeGarden_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Button_Change {
            get {
                return ResourceManager.GetString("Button_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Button_Done {
            get {
                return ResourceManager.GetString("Button_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Button_Keep {
            get {
                return ResourceManager.GetString("Button_Keep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Button_Ok {
            get {
                return ResourceManager.GetString("Button_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Button_Send {
            get {
                return ResourceManager.GetString("Button_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Button_Submit {
            get {
                return ResourceManager.GetString("Button_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Button_WifiSetting {
            get {
                return ResourceManager.GetString("Button_WifiSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasword change.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactive.
        /// </summary>
        public static string Deactive {
            get {
                return ResourceManager.GetString("Deactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting - Deactive.
        /// </summary>
        public static string DeactiveMode_Title {
            get {
                return ResourceManager.GetString("DeactiveMode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string Device_Title {
            get {
                return ResourceManager.GetString("Device_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new device.
        /// </summary>
        public static string Device_ToolbarItemAdd {
            get {
                return ResourceManager.GetString("Device_ToolbarItemAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After garden.
        /// </summary>
        public static string Device_ToolbarItemDown {
            get {
                return ResourceManager.GetString("Device_ToolbarItemDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous garden.
        /// </summary>
        public static string Device_ToolbarItemUp {
            get {
                return ResourceManager.GetString("Device_ToolbarItemUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string DeviceChart_Title {
            get {
                return ResourceManager.GetString("DeviceChart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string DeviceInformation_Title {
            get {
                return ResourceManager.GetString("DeviceInformation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string DeviceMode_Title {
            get {
                return ResourceManager.GetString("DeviceMode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Dialog_Error_Title {
            get {
                return ResourceManager.GetString("Dialog_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temprature sensor.
        /// </summary>
        public static string DV20180430001 {
            get {
                return ResourceManager.GetString("DV20180430001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... sensor.
        /// </summary>
        public static string DV20180430002 {
            get {
                return ResourceManager.GetString("DV20180430002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light sensor.
        /// </summary>
        public static string DV20180430003 {
            get {
                return ResourceManager.GetString("DV20180430003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hu sensor.
        /// </summary>
        public static string DV20180430004 {
            get {
                return ResourceManager.GetString("DV20180430004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit garden.
        /// </summary>
        public static string EditGarden_Title {
            get {
                return ResourceManager.GetString("EditGarden_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password reset link will be sent to your email to reset your password. If you don&apos;t get an email within a few minutes, please re-try..
        /// </summary>
        public static string ForgotPassword_Description {
            get {
                return ResourceManager.GetString("ForgotPassword_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ForgotPassword_Email {
            get {
                return ResourceManager.GetString("ForgotPassword_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        public static string ForgotPassword_Tenant {
            get {
                return ResourceManager.GetString("ForgotPassword_Tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot pasword.
        /// </summary>
        public static string ForgotPassword_Title {
            get {
                return ResourceManager.GetString("ForgotPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garden.
        /// </summary>
        public static string Garden_Title {
            get {
                return ResourceManager.GetString("Garden_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new garden.
        /// </summary>
        public static string Garden_ToolbarItem {
            get {
                return ResourceManager.GetString("Garden_ToolbarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garden device.
        /// </summary>
        public static string GardenDevice_Title {
            get {
                return ResourceManager.GetString("GardenDevice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string GardenDevices_Title {
            get {
                return ResourceManager.GetString("GardenDevices_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modes.
        /// </summary>
        public static string GardenModes_Title {
            get {
                return ResourceManager.GetString("GardenModes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information_Title {
            get {
                return ResourceManager.GetString("Information_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language_Title {
            get {
                return ResourceManager.GetString("Language_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List null or empty.
        /// </summary>
        public static string ListNullOrEmpty {
            get {
                return ResourceManager.GetString("ListNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or password you inputed is incorrect. Plaese try again .
        /// </summary>
        public static string Login_Failed {
            get {
                return ResourceManager.GetString("Login_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string Login_ForgotPassword {
            get {
                return ResourceManager.GetString("Login_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_LoginButton {
            get {
                return ResourceManager.GetString("Login_LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_PlaceholePassword {
            get {
                return ResourceManager.GetString("Login_PlaceholePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Login_PlaceholeUsername {
            get {
                return ResourceManager.GetString("Login_PlaceholeUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register a new membership!.
        /// </summary>
        public static string Login_Register {
            get {
                return ResourceManager.GetString("Login_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Login_Username {
            get {
                return ResourceManager.GetString("Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Menu_Logout {
            get {
                return ResourceManager.GetString("Menu_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode device.
        /// </summary>
        public static string Menu_ModeDevice {
            get {
                return ResourceManager.GetString("Menu_ModeDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode garden.
        /// </summary>
        public static string Menu_ModeGarden {
            get {
                return ResourceManager.GetString("Menu_ModeGarden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Menu_Setting {
            get {
                return ResourceManager.GetString("Menu_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string MenuItemDelete {
            get {
                return ResourceManager.GetString("MenuItemDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string MenuItemEdit {
            get {
                return ResourceManager.GetString("MenuItemEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode device.
        /// </summary>
        public static string ModeDevice_Title {
            get {
                return ResourceManager.GetString("ModeDevice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode garden.
        /// </summary>
        public static string ModeGarden_Title {
            get {
                return ResourceManager.GetString("ModeGarden_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        public static string Profile_DisplayName {
            get {
                return ResourceManager.GetString("Profile_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile edit.
        /// </summary>
        public static string Profile_Edit_Title {
            get {
                return ResourceManager.GetString("Profile_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Profile_Name {
            get {
                return ResourceManager.GetString("Profile_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string Profile_PhoneNumber {
            get {
                return ResourceManager.GetString("Profile_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Profile_Surname {
            get {
                return ResourceManager.GetString("Profile_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile_Title {
            get {
                return ResourceManager.GetString("Profile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Register_Address {
            get {
                return ResourceManager.GetString("Register_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Register_City {
            get {
                return ResourceManager.GetString("Register_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed information.
        /// </summary>
        public static string Register_DeInfor {
            get {
                return ResourceManager.GetString("Register_DeInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string Register_District {
            get {
                return ResourceManager.GetString("Register_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of bird.
        /// </summary>
        public static string Register_DoB {
            get {
                return ResourceManager.GetString("Register_DoB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Register_Email {
            get {
                return ResourceManager.GetString("Register_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Register_Gender {
            get {
                return ResourceManager.GetString("Register_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone.
        /// </summary>
        public static string Register_HomePhone {
            get {
                return ResourceManager.GetString("Register_HomePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account information.
        /// </summary>
        public static string Register_Infor {
            get {
                return ResourceManager.GetString("Register_Infor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Register_Name {
            get {
                return ResourceManager.GetString("Register_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Register_Password {
            get {
                return ResourceManager.GetString("Register_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Register_PhoneNumber {
            get {
                return ResourceManager.GetString("Register_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Register_Repassword {
            get {
                return ResourceManager.GetString("Register_Repassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created successfully.
        /// </summary>
        public static string Register_UserCreate {
            get {
                return ResourceManager.GetString("Register_UserCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User isn&apos;t created.
        /// </summary>
        public static string Register_UsernotCreate {
            get {
                return ResourceManager.GetString("Register_UsernotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to restart the app after change the language.
        /// </summary>
        public static string Setting_Language_Message {
            get {
                return ResourceManager.GetString("Setting_Language_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language?.
        /// </summary>
        public static string Setting_Language_Title {
            get {
                return ResourceManager.GetString("Setting_Language_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time End.
        /// </summary>
        public static string TimeEnd {
            get {
                return ResourceManager.GetString("TimeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Start.
        /// </summary>
        public static string TimeStart {
            get {
                return ResourceManager.GetString("TimeStart", resourceCulture);
            }
        }
    }
}
